name: test-suite
on: [push, pull_request]
jobs:
  lint-python:
    name: lint-python
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v1
      with:
        python-version: '3.8'
        architecture: 'x64'
    - name: Install flake8
      run: |
        pip install flake8
    - name: Lint python with flake8
      run: |
        flake8 . --max-complexity=10 --statistics

  test-master:
    name: test-asreview-latest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: asr-semantic-clustering
    - uses: actions/checkout@v2
      with:
        repository: asreview/asreview
        path: asr-core
    - uses: actions/setup-python@v1
      with:
        python-version: '3.8'
        architecture: 'x64'
    - name: Install packages and run tests
      run: |
        pip install pytest
        pip install --upgrade setuptools>=41.0.0
        pip install ./asr-core[all]
        pip install ./asr-semantic-clustering
        pytest asr-semantic-clustering/tests